image: ghcr.io/attuneengineering/ai-builder:main
ports:
  - port: 8888
    onOpen: ignore
  - port: 5000
    onOpen: ignore
tasks:
  - init: export HISTFILE=/workspace/.gitpod/cmd-history
  - command: cowsay namaste 🙏
  - command: echo "To launch Jupyter Lab, run '/workspace/ai-builder/bin/launch-jupyter.sh'."


