image: ghcr.io/attuneengineering/ai-builder:main
ports:
  - port: 8888
    onOpen: ignore
  - port: 5000
    onOpen: ignore
tasks:
  - init: git remote set-url origin https://$GITHUB_TOKEN@github.com/AttuneEngineering/ai-builder.git
  - command: echo "alias launch-jupyter='source /workspace/ai-builder/bin/gitpod-jupyter-lab.sh'" >> ~/.bashrc && source ~/.bashrc
  - command: cowsay namaste 🙏
