name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .github/workflows/**
      - requirements.txt

env:
  DOCKER_BUILDKIT: 1

permissions:
  contents: read
  packages: write

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - name: Get the current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Lowercase the repo name and username
        run: echo "REPO=${{ secrets.REGISTRY_IMAGE,,}}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REPO }}:main-${{ env.CURRENT_DATE }}
            ${{ env.REPO }}:main
          cache-from: |
            ${{ env.REPO }}:main
          cache-to: |
            ${{ env.REPO }}:main
